### ISSUE TITLE
AttributeError: 'CorrectorElmoSCLstm' object has no attribute 'finetune'

### ISSUE THREAD

**Issue by Shivanandroy** [neuspell/neuspell#12]
I was trying to run
```python
""" load spell checkers """
from neuspell import SclstmChecker
checker = SclstmChecker()
checker = checker.add_("elmo", at="input")
checker.from_pretrained("./data/checkpoints/elmoscrnn-probwordnoise")

""" spell correction """
checker.correct("I luk foward to receving your reply")
# → ["I look forward to receiving your reply"]


""" fine-tuning on domain specific dataset """
checker.finetune(clean_file="clean.txt", corrupt_file="corrupt.txt")
```

**Comment by Shivanandroy** [comment]
Hi @neuspell Team - I would really appreciate if you can help us in the issue above in any form

**Comment by murali1996** [comment]
Hi @Shivanandroy, the latest version of code now supports fine-tuning in the following two models - `BERT` and `SC-LSTM plus ELMO (at input)`. You can refer to the quick-start code snippet in the readme for running the same. Sample datasets are provided in the folder `./data/traintest` as `sample_*.txt` files. Please follow the same data format (one input per line) for fine-tuning. The fine-tuning snippets for other models will be added soon and are very similar to the above two models' finetuning.

I am closing this issue for now. Feel free to raise any other issues you come across. Thanks.
