### ISSUE TITLE
Git clone fails on Windows

### ISSUE THREAD

**Issue by bidwej** [neuspell/neuspell#14]
FYI - Git clone fails on windows when following the installation instructions.

  D:\workspace>git clone https://github.com/neuspell/neuspell.git
  Cloning into 'neuspell'...
  remote: Enumerating objects: 235, done.
  remote: Counting objects: 100% (235/235), done.
  remote: Compressing objects: 100% (145/145), done.
  Receote: Total 432 (delta 142), reused 159 (delta 82), pack-reused 197eceiving objects:                             6.05 MiB/s
  Receiving objects: 100% (432/432), 74.34 MiB | 6.26 MiB/s, done.
  Resolving deltas: 100% (168/168), done.
  error: invalid path 'applications/Adversarial-Misspellings/defenses/scRNN/model_dumps/scrnn_TASK_NAME=MRPC__VOCAB_SIZE=9999_REP_LIST=swap_key_add_drop_REP_PROBS=0.25:0.25:0.25:0.25'
  fatal: unable to checkout working tree
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

I had to add the following to my git config to perform a sparse checkout
 git config core.protectNTFS false

https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows

**Comment by murali1996** [comment]
Hi @bidwej. Thanks for raising the issue. The codebase is updated to resolve this issue. (#19) So after the update, the applications folder can be optionally populated.
