### ISSUE TITLE
Modify readme

### ISSUE THREAD

**Issue by aswin-giridhar** [neuspell/neuspell#15]
```
Download datasets
Run the following to download datasets

cd data/traintest
python download_dataset.py 
See data/traintest/README.md for more details.
```

The `python download_dataset.py ` must be changed to `python download_datafiles.py` as there is no python download_dataset.py in trainset

**Comment by murali1996** [comment]
Thanks for pointing it out. Addressed in the latest [commit](https://github.com/neuspell/neuspell/commit/f1d1a8b4efa7c6aa6e0564ea17db152905f4c7dc).
