### ISSUE TITLE
Deployment errors when pushing to GCP

### ISSUE THREAD

**Issue by jonnyjohnson1** [neuspell/neuspell#17]
I have wrapped neuspell in a simple flask app, put it in a Docker container, and am deploying to GCP.

It is saying there is a memory leak somewhere. The app downloads a couple things then downloads a 1.52GB file, which I think is happening on these steps:

`from __future__ import unicode_literals, print_function
from neuspellMast.neuspell import ElmosclstmChecker #BertsclstmChecker, SclstmChecker, 

checker = ElmosclstmChecker()

checker.from_pretrained("./neuspellMast/data/checkpoints/elmoscrnn-probwordnoise")
`
I know there could be a lot going on in this set up to cause this, but I wonder if anyone else has encountered this kind of thing when deploying the code.

**Comment by murali1996** [comment]
Hi @jonnyjohnson1, the `ElmosclstmChecker` downloads the ELMO model. The 1.52 GB file is the ELMO model's pre-trained weights. This is true for any `neuspell` model that includes ELMO model and is only downloaded the first time. This download is automatic when the ELMO model is being initialized, if no local path is provided ([allennlp code reference](https://github.com/allenai/allennlp/blob/decb875b4129ee9e6e286c9eea5f51b3f453c944/allennlp/modules/elmo.py#L41)). Hence, to offer a solution to your issue, you can download the required files prior to using a spell-checker and then use the checkers as usual.

```bash
cd data
mkdir allennlp_elmo_pretrained; cd allennlp_elmo_pretrained
wget https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json
wget https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5
```

Once downloaded, you can use:
```python
from neuspell import ElmosclstmChecker
checker = ElmosclstmChecker()
checker.from_pretrained()
checker.correct("I luk foward to receving your reply")
```

**Comment by murali1996** [comment]
Hi @jonnyjohnson1, I am closing this issue for now. Feel free to re-open if the problem persists.

**Comment by jonnyjohnson1** [comment]
@murali1996 Great. I'll get to check it out this week.

**Comment by draftin1** [comment]
@murali1996

I finally got to dig deeper into this, and I'm unable to get this working locally.

I've tried this code, starting in a fresh conda environment.

```
git clone https://github.com/neuspell/neuspell; cd neuspell
pip install -e .

pip install -r extras-requirements.txt

cd data
mkdir allennlp_elmo_pretrained; cd allennlp_elmo_pretrained
wget https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json
wget https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5

cd ..
cd ..
cd ..

```


```python
from neuspell import ElmosclstmChecker
checker = ElmosclstmChecker()
checker.from_pretrained()  # <---- Fails here
checker.correct("I luk foward to receving your reply")

#tried these too
checker.from_pretrained("./neuspell/data/checkpoints/elmoscrnn-probwordnoise")
checker.from_pretrained("./neuspell/data/allennlp_elmo_pretrained", "./neuspell/data/checkpoints/elmoscrnn-probwordnoise/vocab.pkl")

```

I keep getting this error:

  File "/anaconda3/envs/spellcheck/lib/python3.8/site-packages/torch/serialization.py", line 587, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/anaconda3/envs/spellcheck/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
