### ISSUE TITLE
SSL Error when downloading pretrained models.

### ISSUE THREAD

**Issue by MustafaCelen** [neuspell/neuspell#24]
Hi, 
when Im trying to download a pretrained model with this code: 
### neuspell.seq_modeling.downloads.download_pretrained_model("bertscrnn-probwordnoise")

I got the below error:

### HTTPSConnectionPool(host='doc-00-30-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/gti2smdi6shae5s5bikom49c1e0n4qi9/1eg6pp6pp509p1las4ukmsh31e9djdnd/1618470150000/02761850238464772402/13110869053472900530Z/1nMyoXg49_dl_jiXt9bFo8A4Gnd9XdGD2?e=download (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1091)')))

also same with every other model obviously since its a SSL error , any idea why its happening ? I am using my work laptop which has bunch of restrictions , can it be that ?

**Comment by murali1996** [comment]
Hi @MustafaCelen, can you try changing the following lines in "neuspell/seq_modeling/downloads.py" and installing locally using `pip install -e .` to see if the issue gets resolved?

[line 14](https://github.com/neuspell/neuspell/blob/ff9c112851ad526607d8ceaa5bea31d2751f353e/neuspell/seq_modeling/downloads.py#L14)   
from `response = session.get(URL, params={'id': id}, stream=True)`    
to `response = session.get(URL, params={'id': id}, stream=True, verify=False)`

Similarly add `verify=False` in [line 19](https://github.com/neuspell/neuspell/blob/ff9c112851ad526607d8ceaa5bea31d2751f353e/neuspell/seq_modeling/downloads.py#L19) as well.

**Comment by MustafaCelen** [comment]
wow amazing response time thank you for that :) 

https://slproweb.com/products/Win32OpenSSL.html 

I downloaded openssl from the link solved my issue actually , thanks again for all your hard work.

**Comment by MustafaCelen** [comment]
Amazing response time :) , thank you for your solution , it worked for me.
