### ISSUE TITLE
Changing Epoch

### ISSUE THREAD

**Issue by ByUnal** [neuspell/neuspell#50]
How to increase or decrease epoch number while fine tunning ?

**Comment by kailashkarthiks** [comment]
Did you try setting the `n_epochs` arg in the finetune method? https://github.com/neuspell/neuspell/blob/master/neuspell/corrector_subwordbert.py#L77

**Comment by ByUnal** [comment]
@kailashkarthiks Yes, I solved it by doing that. Thnx anyway.
