### ISSUE TITLE
Demo server broken ?

### ISSUE THREAD

**Issue by WilliamTambellini** [neuspell/neuspell#8]
When browsing
http://neuspell.github.io/

"Impossible to connect to 
http://ogma.lti.cs.cmu.edu:5000/
"

**Comment by murali1996** [comment]
Hi @WilliamTambellini The server will be down for some days now. However, you can easily run the flask-server on your own machine by following the demo setup page [here](https://github.com/neuspell/neuspell#Demo-Setup). The code can run on CPU as well as GPU.
